# Generated by Django 5.0.2 on 2024-02-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_d_agegrp_d_date_d_departement_d_federation_d_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_City',
            fields=[
                ('postal_code', models.CharField(default=None, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=300)),
                ('department', models.CharField(default=None, max_length=300)),
                ('region', models.CharField(default=None, max_length=300)),
                ('country', models.CharField(default=None, max_length=300)),
            ],
        ),
    ]
